#!/bin/bash
# run this as the predictor user!

WDIR="`dirname $0`/../"
VIRTUALENV_DIR=$WDIR

source $VIRTUALENV_DIR/bin/activate
export CHEMAXON_LICENSE_URL=$WDIR/SETUP/license.cxl
cd $WDIR
python modeler.py
